-- Los Angeles area tennis courts seed
INSERT INTO courts (
  name, address, latitude, longitude,
  court_type, cost, booking_method, number_of_courts,
  surface, has_lights, hours, net_condition,
  has_restrooms, parking_info, best_times, junior_notes
) VALUES

('Griffith Park Tennis Courts',
 '3700 W Riverside Dr, Los Angeles, CA 90027',
 34.1341, -118.2785,
 'PUBLIC_FREE', 'Free', 'First-come, first-served', 12,
 'Hard', true, '7am–9pm daily',
 'GOOD', true,
 'Free parking in the park lots off Riverside Dr.',
 'Early mornings and late evenings on weekdays',
 'Popular with juniors. Courts closest to the main lot fill up fastest on weekends.'),

('Balboa Tennis Courts',
 '17015 Burbank Blvd, Encino, CA 91316',
 34.1665, -118.5005,
 'PUBLIC_FREE', 'Free', 'First-come, first-served', 8,
 'Hard', true, '7am–10pm daily',
 'GOOD', true,
 'Large free parking lot on site.',
 'Weekday afternoons after 3pm',
 'Well-lit courts, great for evening practice. Very USTA-active community.'),

('Cheviot Hills Recreation Center',
 '2551 Motor Ave, Los Angeles, CA 90064',
 34.0370, -118.4167,
 'PUBLIC_FREE', 'Free', 'First-come, first-served', 8,
 'Hard', false, '7am–dusk daily',
 'GOOD', true,
 'Street parking on Motor Ave and Manning Ave.',
 'Weekend mornings arrive by 8am',
 'Popular Westside courts. Courts fill early on weekends — arrive early.'),

('La Cienega Tennis Center',
 '325 S La Cienega Blvd, Beverly Hills, CA 90211',
 34.0670, -118.3740,
 'PUBLIC_PAY', '$4/hr resident · $8/hr non-resident', 'Reserve via Beverly Hills Parks & Rec', 14,
 'Hard', true, '7am–10pm daily',
 'GOOD', true,
 'Underground parking structure at the facility.',
 'Weekday mornings and evenings',
 'One of the best-maintained public facilities in LA. Frequent junior clinics and USTA matches held here.'),

('Barrington Recreation Center',
 '333 S Barrington Ave, Los Angeles, CA 90049',
 34.0570, -118.4717,
 'PUBLIC_FREE', 'Free', 'First-come, first-served', 4,
 'Hard', false, '7am–dusk daily',
 'FAIR', true,
 'Small lot on site plus street parking.',
 'Early weekday mornings',
 'Quiet neighborhood courts, rarely crowded on weekday mornings.'),

('Silver Lake Recreation Center',
 '1850 W Silver Lake Dr, Los Angeles, CA 90026',
 34.0866, -118.2663,
 'PUBLIC_FREE', 'Free', 'First-come, first-served', 4,
 'Hard', true, '7am–9pm daily',
 'FAIR', true,
 'Street parking along Silver Lake Dr.',
 'Weekday evenings',
 'Lights make it great for after-school practice.'),

('Holmby Park Tennis Courts',
 '601 Club View Dr, Los Angeles, CA 90024',
 34.0641, -118.4289,
 'PUBLIC_FREE', 'Free', 'First-come, first-served', 4,
 'Hard', false, '7am–dusk daily',
 'GOOD', true,
 'Free parking inside Holmby Park.',
 'Weekday mornings',
 'Quiet park setting near UCLA. Good surface, rarely crowded.'),

('Elysian Park Tennis Courts',
 '929 Academy Rd, Los Angeles, CA 90012',
 34.0789, -118.2382,
 'PUBLIC_FREE', 'Free', 'First-come, first-served', 6,
 'Hard', false, '7am–dusk daily',
 'FAIR', false,
 'Free parking inside the park.',
 'Weekday mornings',
 'Scenic courts inside the park. Bring your own water — no fountain nearby.'),

('UCLA Los Angeles Tennis Center',
 '555 Westwood Plaza, Los Angeles, CA 90095',
 34.0723, -118.4490,
 'PUBLIC_PAY', '$10–15/hr (call ahead)', 'Call UCLA Recreation at (310) 825-2688', 16,
 'Hard', true, 'Varies by season',
 'GOOD', true,
 'UCLA Parking Structure 8 nearby (paid).',
 'Non-game-day mornings',
 'Division I facility. Occasionally open to the public when no team events. Worth calling ahead — great surface for competitive practice.'),

('Larchmont Village Park',
 '401 N Larchmont Blvd, Los Angeles, CA 90004',
 34.0769, -118.3246,
 'PUBLIC_FREE', 'Free', 'First-come, first-served', 2,
 'Hard', false, '7am–dusk daily',
 'FAIR', false,
 'Street parking on Larchmont Blvd.',
 'Weekday mornings',
 'Only 2 courts — best for a guaranteed game on weekdays.'),

('Westwood Recreation Center',
 '1350 S Sepulveda Blvd, Los Angeles, CA 90025',
 34.0454, -118.4450,
 'PUBLIC_FREE', 'Free', 'First-come, first-served', 6,
 'Hard', true, '7am–9pm daily',
 'GOOD', true,
 'Parking lot on site.',
 'Weekday afternoons',
 'Good lights, close to UCLA. After-school rush — weekday mornings are much quieter.'),

('Poinsettia Recreation Center',
 '7341 Willoughby Ave, Los Angeles, CA 90046',
 34.0873, -118.3547,
 'PUBLIC_FREE', 'Free', 'First-come, first-served', 4,
 'Hard', true, '7am–9pm daily',
 'FAIR', true,
 'Street parking on Willoughby Ave.',
 'Weekday evenings',
 'Lights and decent nets. Popular with the West Hollywood tennis community.'),

('Roxbury Park',
 '471 S Roxbury Dr, Beverly Hills, CA 90212',
 34.0603, -118.4000,
 'PUBLIC_FREE', 'Free', 'First-come, first-served', 6,
 'Hard', true, '7am–10pm daily',
 'GOOD', true,
 'Free parking lot inside the park.',
 'Evening weekdays after 5pm',
 'Well-maintained Beverly Hills facility. Lights are reliable. Good community.'),

('Brentwood Recreation Center',
 '100 S Saltair Ave, Los Angeles, CA 90049',
 34.0520, -118.4760,
 'PUBLIC_FREE', 'Free', 'First-come, first-served', 4,
 'Hard', false, '7am–dusk daily',
 'GOOD', true,
 'Small lot on site plus street parking.',
 'Early weekday mornings',
 'Quiet neighborhood park. Courts in good shape.'),

('Exposition Park Tennis Courts',
 '700 Exposition Park Dr, Los Angeles, CA 90037',
 34.0164, -118.2882,
 'PUBLIC_FREE', 'Free', 'First-come, first-served', 8,
 'Hard', false, '7am–dusk daily',
 'FAIR', true,
 'Paid parking lots in Exposition Park ($8–12).',
 'Weekday mornings',
 'Near USC. Can get busy on event days at the Coliseum — check the calendar.'),

('MacArthur Park Tennis Courts',
 '2230 W 6th St, Los Angeles, CA 90057',
 34.0573, -118.2771,
 'PUBLIC_FREE', 'Free', 'First-come, first-served', 4,
 'Hard', false, '7am–dusk daily',
 'FAIR', false,
 'Street parking on 6th St.',
 'Weekday mornings',
 'Courts are functional but basic. Good option if other courts are full.'),

('Lincoln Park Tennis Courts',
 '3501 Valley Blvd, Los Angeles, CA 90031',
 34.0748, -118.2117,
 'PUBLIC_FREE', 'Free', 'First-come, first-served', 6,
 'Hard', true, '7am–9pm daily',
 'FAIR', true,
 'Free parking inside Lincoln Park.',
 'Weekday evenings',
 'Lights available. Active East LA tennis community.'),

('El Camino Real Park',
 '22400 Clarendon St, Woodland Hills, CA 91367',
 34.1753, -118.6090,
 'PUBLIC_FREE', 'Free', 'First-come, first-served', 8,
 'Hard', true, '7am–9pm daily',
 'GOOD', true,
 'Free parking inside the park.',
 'Weekday mornings and evenings',
 'Great San Fernando Valley courts. Well-lit and in good condition. Active junior community in this area.'),

('Venice Beach Tennis Courts',
 '1800 Ocean Front Walk, Venice, CA 90291',
 33.9850, -118.4722,
 'PUBLIC_FREE', 'Free', 'First-come, first-served', 6,
 'Hard', false, '7am–dusk daily',
 'FAIR', false,
 'Paid street/lot parking — arrive early on weekends.',
 'Early weekday mornings before the beach crowds arrive',
 'Iconic courts on the boardwalk. Fun atmosphere but windy. Best for casual rallying rather than serious match prep.'),

('Downey Recreation Center Tennis Courts',
 '11531 Brookshire Ave, Downey, CA 90241',
 33.9402, -118.1324,
 'PUBLIC_FREE', 'Free', 'First-come, first-served', 8,
 'Hard', true, '7am–9pm daily',
 'GOOD', true,
 'Free parking at the recreation center.',
 'Weekday afternoons and evenings',
 'Good South LA option. Lights and solid nets. Active local tennis program.');
